amcl:
  ros__parameters:
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    always_reset_initial_pose: false
    base_frame_id: base_footprint
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    first_map_only: false
    global_frame_id: map
    initial_pose:
      x: 0.0
      y: 0.0
      yaw: 0.0
      z: 0.0
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 100.0
    laser_min_range: -1.0
    laser_model_type: likelihood_field
    map_topic: map
    max_beams: 60
    max_particles: 2000
    min_particles: 500
    odom_frame_id: odom
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: nav2_amcl::DifferentialMotionModel
    save_pose_rate: 0.5
    scan_topic: scan
    set_initial_pose: false
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 0.5
    update_min_a: 0.2
    update_min_d: 0.25
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05
behavior_server:
  ros__parameters:
    assisted_teleop:
      plugin: nav2_behaviors::AssistedTeleop
    backup:
      plugin: nav2_behaviors::BackUp
    behavior_plugins:
    - spin
    - backup
    - drive_on_heading
    - wait
    - assisted_teleop
    cycle_frequency: 10.0
    drive_on_heading:
      plugin: nav2_behaviors::DriveOnHeading
    enable_stamped_cmd_vel: true
    global_costmap_topic: global_costmap/costmap_raw
    global_footprint_topic: global_costmap/published_footprint
    global_frame: map
    local_costmap_topic: local_costmap/costmap_raw
    local_footprint_topic: local_costmap/published_footprint
    local_frame: odom
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    robot_base_frame: base_link
    rotational_acc_lim: 3.2
    simulate_ahead_time: 2.0
    spin:
      plugin: nav2_behaviors::Spin
    transform_timeout: 0.1
    wait:
      plugin: nav2_behaviors::Wait
bt_navigator:
  ros__parameters:
    always_reload_bt_xml: false
    default_nav_through_poses_bt_xml: $(find-pkg-share nav2_bt_navigator)/behavior_trees/navigate_to_pose_w_replanning_and_recovery.xml
    default_nav_to_pose_bt_xml: $(find-pkg-share nav2_bt_navigator)/behavior_trees/navigate_to_pose_w_replanning_and_recovery.xml
    error_code_name_prefixes:
    - assisted_teleop
    - backup
    - compute_path
    - dock_robot
    - drive_on_heading
    - follow_path
    - nav_thru_poses
    - nav_to_pose
    - spin
    - route
    - undock_robot
    - wait
    filter_duration: 0.3
    global_frame: map
    goal_blackboard_id: goal
    goals_blackboard_id: goals
    navigate_through_poses:
      plugin: nav2_bt_navigator::NavigateThroughPosesNavigator
    navigate_to_pose:
      plugin: nav2_bt_navigator::NavigateToPoseNavigator
    navigators:
    - navigate_to_pose
    - navigate_through_poses
    path_blackboard_id: path
    robot_base_frame: base_link
    transform_tolerance: 0.5
collision_monitor:
  ros__parameters:
    FootprintApproach:
      action_type: approach
      enabled: false
      footprint_topic: /local_costmap/published_footprint
      min_points: 6
      simulation_time_step: 0.02
      time_before_collision: 2.0
      type: polygon
      visualize: false
    PolygonLimit:
      action_type: limit
      angular_limit: 0.5
      enabled: false
      linear_limit: 0.4
      min_points: 4
      points: '[[0.1, 0.1], [0.1, -0.1], [-0.1, -0.1], [-0.1, 0.1]]'
      polygon_pub_topic: polygon_limit
      type: polygon
      visualize: true
    PolygonSlow:
      action_type: slowdown
      enabled: false
      min_points: 4
      points: '[[0.1, 0.1], [0.1, -0.1], [-0.1, -0.1], [-0.1, 0.1]]'
      polygon_pub_topic: polygon_slowdown
      slowdown_ratio: 0.3
      type: polygon
      visualize: true
    PolygonStop:
      action_type: stop
      enabled: false
      min_points: 4
      polygon_pub_topic: polygon_stop
      radius: 0.1
      type: circle
      visualize: true
    VelocityPolygonStop:
      action_type: stop
      enabled: false
      holonomic: false
      min_points: 6
      polygon_pub_topic: velocity_polygon_stop
      rotation:
        linear_max: 0.05
        linear_min: 0.0
        points: '[[0.3, 0.3], [0.3, -0.3], [-0.3, -0.3], [-0.3, 0.3]]'
        theta_max: 1.0
        theta_min: -1.0
      stopped:
        linear_max: 1.0
        linear_min: -1.0
        points: '[[0.25, 0.25], [0.25, -0.25], [-0.25, -0.25], [-0.25, 0.25]]'
        theta_max: 1.0
        theta_min: -1.0
      translation_backward:
        linear_max: 0.0
        linear_min: -1.0
        points: '[[0.2, 0.3], [0.2, -0.3], [-0.35, -0.3], [-0.35, 0.3]]'
        theta_max: 1.0
        theta_min: -1.0
      translation_forward:
        linear_max: 1.0
        linear_min: 0.0
        points: '[[0.35, 0.3], [0.35, -0.3], [-0.2, -0.3], [-0.2, 0.3]]'
        theta_max: 1.0
        theta_min: -1.0
      type: velocity_polygon
      velocity_polygons:
      - rotation
      - translation_forward
      - translation_backward
      - stopped
      visualize: true
    base_frame_id: base_footprint
    base_shift_correction: true
    cmd_vel_in_topic: cmd_vel_smoothed
    cmd_vel_out_topic: cmd_vel
    enable_stamped_cmd_vel: true
    observation_sources:
    - scan
    odom_frame_id: odom
    polygons:
    - PolygonStop
    - PolygonSlow
    - FootprintApproach
    scan:
      enabled: true
      source_timeout: 0.2
      topic: /scan
      type: scan
    source_timeout: 5.0
    state_topic: collision_monitor_state
    stop_pub_timeout: 2.0
    transform_tolerance: 0.5
    use_realtime_priority: false
controller_server:
  ros__parameters:
    FollowPath:
      BaseObstacle.scale: 0.02
      GoalAlign.forward_point_distance: 0.1
      GoalAlign.scale: 5.0
      GoalDist.scale: 12.0
      PathAlign.forward_point_distance: 0.1
      PathAlign.scale: 0.0
      PathDist.scale: 16.0
      RotateToGoal.lookahead_time: -1.0
      RotateToGoal.scale: 32.0
      RotateToGoal.slowing_factor: 5.0
      acc_lim_theta: 3.2
      acc_lim_x: 3.0
      acc_lim_y: 0.0
      angular_granularity: 0.025
      critics:
      - RotateToGoal
      - Oscillation
      - BaseObstacle
      - GoalAlign
      - PathAlign
      - PathDist
      - GoalDist
      debug_trajectory_details: true
      decel_lim_theta: -3.2
      decel_lim_x: -2.5
      decel_lim_y: 0.0
      linear_granularity: 0.05
      max_speed_xy: 0.6
      max_vel_theta: 2.0
      max_vel_x: 0.6
      max_vel_y: 0.0
      min_speed_theta: 0.0
      min_speed_xy: 0.0
      min_vel_x: 0.0
      min_vel_y: 0.0
      plugin: dwb_core::DWBLocalPlanner
      short_circuit_trajectory_evaluation: true
      sim_time: 0.8
      stateful: true
      trans_stopped_velocity: 0.25
      transform_tolerance: 0.2
      vtheta_samples: 60
      vx_samples: 30
      vy_samples: 0
      xy_goal_tolerance: 0.05
    controller_frequency: 15.0
    controller_plugins:
    - FollowPath
    enable_stamped_cmd_vel: true
    failure_tolerance: 0.3
    goal_checker:
      plugin: nav2_controller::SimpleGoalChecker
      stateful: true
      xy_goal_tolerance: 0.05
      yaw_goal_tolerance: 0.05
    goal_checker_plugins:
    - goal_checker
    min_theta_velocity_threshold: 0.001
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.001
    progress_checker:
      movement_time_allowance: 10.0
      plugin: nav2_controller::SimpleProgressChecker
      required_movement_radius: 0.1
    progress_checker_plugins:
    - progress_checker
docking_server:
  ros__parameters:
    dock_plugins:
    - nova_carter_dock
    docks:
    - home_dock
    - flex_dock1
    - flex_dock2
    enable_stamped_cmd_vel: true
    flex_dock1:
      frame: map
      pose:
      - 10.0
      - 10.0
      - 0.0
      type: nova_carter_dock
    flex_dock2:
      frame: map
      pose:
      - 30.0
      - 30.0
      - 0.0
      type: nova_carter_dock
    home_dock:
      frame: map
      pose:
      - 0.0
      - 0.0
      - 0.0
      type: nova_carter_dock
    nova_carter_dock:
      plugin: opennav_docking::SimpleChargingDock
global_costmap:
  global_costmap:
    ros__parameters:
      always_send_full_costmap: true
      global_frame: map
      inflation_layer:
        cost_scaling_factor: 2.5
        inflation_radius: 0.15
        plugin: nav2_costmap_2d::InflationLayer
      obstacle_layer:
        enabled: true
        observation_sources: scan
        plugin: nav2_costmap_2d::ObstacleLayer
        scan:
          clearing: true
          data_type: LaserScan
          marking: true
          max_obstacle_height: 2.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          topic: /scan
      plugins:
      - static_layer
      - obstacle_layer
      - voxel_layer
      - inflation_layer
      publish_frequency: 1.0
      resolution: 0.05
      robot_base_frame: base_link
      robot_radius: 0.1
      static_layer:
        map_subscribe_transient_local: true
        plugin: nav2_costmap_2d::StaticLayer
        transform_tolerance: 0.1
      track_unknown_space: true
      transform_tolerance: 0.5
      update_frequency: 1.0
      voxel_layer:
        enabled: true
        mark_threshold: 0
        max_obstacle_height: 2.0
        observation_sources: scan
        origin_z: 0.0
        plugin: nav2_costmap_2d::VoxelLayer
        publish_voxel_map: true
        scan:
          clearing: true
          data_type: LaserScan
          marking: true
          max_obstacle_height: 2.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          topic: /scan
        z_resolution: 0.05
        z_voxels: 16
local_costmap:
  local_costmap:
    ros__parameters:
      always_send_full_costmap: true
      global_frame: odom
      height: 3
      inflation_layer:
        cost_scaling_factor: 2.5
        inflation_radius: 0.3
        plugin: nav2_costmap_2d::InflationLayer
      obstacle_layer:
        enabled: true
        observation_sources: scan
        plugin: nav2_costmap_2d::ObstacleLayer
        scan:
          clearing: true
          data_type: LaserScan
          marking: true
          max_obstacle_height: 2.0
          topic: /scan
      plugins:
      - obstacle_layer
      - voxel_layer
      - inflation_layer
      publish_frequency: 2.0
      resolution: 0.05
      robot_base_frame: base_link
      robot_radius: 0.1
      rolling_window: true
      static_layer:
        map_subscribe_transient_local: true
      update_frequency: 5.0
      voxel_layer:
        enabled: true
        mark_threshold: 0
        max_obstacle_height: 2.0
        observation_sources: scan
        origin_z: 0.0
        plugin: nav2_costmap_2d::VoxelLayer
        publish_voxel_map: true
        scan:
          clearing: true
          data_type: LaserScan
          marking: true
          max_obstacle_height: 2.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          topic: /scan
        z_resolution: 0.05
        z_voxels: 16
      width: 3
map_saver:
  ros__parameters:
    free_thresh_default: 0.25
    map_subscribe_transient_local: true
    occupied_thresh_default: 0.65
    save_map_timeout: 5.0
map_server:
  ros__parameters:
    yaml_filename: map.yaml
planner_server:
  ros__parameters:
    GridBased:
      allow_unknown: true
      plugin: nav2_navfn_planner::NavfnPlanner
      tolerance: 1.0
      use_astar: false
    expected_planner_frequency: 10.0
    planner_plugins:
    - GridBased
velocity_smoother:
  ros__parameters:
    deadband_velocity:
    - 0.0
    - 0.0
    - 0.0
    enable_stamped_cmd_vel: true
    feedback: OPEN_LOOP
    max_accel:
    - 2.5
    - 0.0
    - 3.2
    max_decel:
    - -2.5
    - 0.0
    - -3.2
    max_velocity:
    - 0.5
    - 0.0
    - 2.5
    min_velocity:
    - -0.5
    - 0.0
    - -2.5
    odom_duration: 0.1
    odom_topic: odom
    scale_velocities: false
    smoothing_frequency: 20.0
    use_realtime_priority: false
    velocity_timeout: 1.0
waypoint_follower:
  ros__parameters:
    loop_rate: 20
    stop_on_failure: false
    wait_at_waypoint:
      enabled: true
      plugin: nav2_waypoint_follower::WaitAtWaypoint
      waypoint_pause_duration: 200
    waypoint_task_executor_plugin: wait_at_waypoint
